application:
  port: 8000
  base_url: "http://127.0.0.1"
redis:
  uri: "redis://127.0.0.1:6379"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "database_name"
  require_ssl: false
